== Typed References

The properties and components defined here can all reference external meta-data
which may be used by applications to provide further information to users. By
providing type information, clients and servers are able to discover interesting
references and make use of them, perhaps for indexing or the presenting of
additional related information for the user.

As always, clients should exercise caution in following references to external
data.

The <<RFC5545>> LOCATION property provides only an unstructured single text value
for specifying the location where an event (or task) will occur. This is
inadequate for use cases where structured location information (e.g. address,
region, country, postal code) is required or preferred, and limits widespread
adoption of iCalendar in those settings.

Using the VLOCATION component, rich information about multiple locations can be
communicated in a STRUCTURED-DATA property, for example, address, region,
country, postal code as well as other information such as parking availability,
nearby restaurants and the venue. Servers and clients can retrieve the objects
when storing the event and use them to index by geographic location.

When a calendar client receives a calendar component it can search the set of
locations looking for those of particular interest. The LOCATION-TYPE property
and STRUCTURED-DATA FMTTYPE parameter, if supplied, can be used to help the
selection.

The PARTICIPANT component is designed to handle common use cases in event
publication. It is generally important to provide information about the
organizers of such events. Sponsors wish to be referenced in a prominent manner.
In social calendaring it is often important to identify the active participants
in the event, for example a school sports team, and the inactive participants,
for example the parents.

The PARTICIPANT component can be used to provide useful extra data about an
attendee. For example a location inside the PARTICIPANT gives the actual location
of a remote attendee. (But see the note about privacy.)

Alternatively the PARTICIPANT component can be used to provide a reference -
perhaps the address for mailing lists.

=== Use Cases

The main motivation for these changes has been event publication but there are
opportunities for use elsewhere. The following use cases will describe some
possible scenarios.

==== Piano Concert Performance

In putting together a concert there are many participants: piano tuner,
performer, stage hands etc. In addition there are sponsors and various contacts
to be provided. There will also be a number of related locations. A number of
events can be created, all of which relate to the performance in different ways.

There may be an iTIP <<RFC5546>> meeting request for the piano tuner who will arrive
before the performance. Other members of staff may also receive meeting requests.

An event can also be created for publication which will have a PARTICIPANT
component for the pianist providing a reference to vCard <<RFC2426>> information
about the performer. This event would also hold information about parking, local
subway stations and the venue itself. In addition, there may be sponsorship
information for sponsors of the event and perhaps paid sponsorship properties
essentially advertising local establishments.

==== Itineraries

These additions also provide opportunities for the travel industry. When booking
a flight the PARTICIPANT component can be used to provide references to
businesses at the airports and to car hire businesses at the destination.

The embedded location information can guide the traveler at the airport or to
their final destination. The contact information can provide detailed information
about the booking agent, the airlines, car hire companies and the hotel.

==== Reserving facilities

For a meeting, the size of a room and the equipment needed depends to some extent
on the number of attendees actually in the room.

A meeting may have many attendees none of which are co-located. The current
ATTENDEE property does not allow for the addition of such meta-data. The
PARTICIPANT component allows attendees to specify their location.
